<?php

namespace App\Model;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable = ['title','body','slug','user_id','category_id'];
//    public function getRouteKeyName()
//    {
//        return 'slug';
//    }
static function boot()
{
    parent::boot(); // TODO: Change the autogenerated stub

  static::creating(function ($question){
   $question->slug = str_slug($question->title);
  });
}

    public function user(){
        return $this->belongsTo(User::class);
    }
    public function replies(){
 return $this->hasMany(Reply::class)->latest();
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function getPathAttribute(){
        return "/question/$this->id";
    }
}
